export interface TemplateConfig {
  id: string
  name: string
  category: string
  emoji: string
  // Background
  bg: string
  bgGradient?: string
  // Text
  textPrimary: string
  textSecondary: string
  textAccent: string
  // Buttons
  btnBg: string
  btnText: string
  btnBorder?: string
  btnRadius: string // 'none' | 'sm' | 'lg' | 'full'
  btnStyle: 'solid' | 'outline' | 'ghost' | 'gradient'
  // Typography
  fontDisplay: string
  fontBody: string
  nameStyle?: string // extra CSS classes
  // Avatar
  avatarBorder?: string
  avatarBg?: string
  // Decorations
  decoration?: 'none' | 'dots' | 'grid' | 'stars' | 'lines' | 'diamonds'
  // Animation
  animated?: boolean
  animationType?: 'gradient' | 'glow' | 'float'
  // Special
  glowColor?: string
  watermarkColor: string
}

export const TEMPLATES: TemplateConfig[] = [
  // ─── MINIMAL / CLEAN ──────────────────────────────────────────────
  {
    id: 'minimal-white',
    name: 'Pure White',
    category: 'Minimal',
    emoji: '⬜',
    bg: '#FFFFFF',
    textPrimary: '#111111',
    textSecondary: '#666666',
    textAccent: '#111111',
    btnBg: '#111111',
    btnText: '#FFFFFF',
    btnRadius: 'sm',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#CCCCCC',
  },
  {
    id: 'minimal-dark',
    name: 'Obsidian',
    category: 'Minimal',
    emoji: '⬛',
    bg: '#0A0A0A',
    textPrimary: '#FFFFFF',
    textSecondary: '#888888',
    textAccent: '#FFFFFF',
    btnBg: '#FFFFFF',
    btnText: '#000000',
    btnRadius: 'sm',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#333333',
  },
  {
    id: 'minimal-stone',
    name: 'Warm Stone',
    category: 'Minimal',
    emoji: '🪨',
    bg: '#F5F0EB',
    textPrimary: '#2C2416',
    textSecondary: '#8B7355',
    textAccent: '#2C2416',
    btnBg: '#2C2416',
    btnText: '#F5F0EB',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#C4B59A',
  },
  {
    id: 'minimal-slate',
    name: 'Slate',
    category: 'Minimal',
    emoji: '🩶',
    bg: '#1E293B',
    textPrimary: '#F1F5F9',
    textSecondary: '#94A3B8',
    textAccent: '#38BDF8',
    btnBg: '#38BDF8',
    btnText: '#0F172A',
    btnRadius: 'lg',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#334155',
  },
  {
    id: 'minimal-rose',
    name: 'Rose Petal',
    category: 'Minimal',
    emoji: '🌸',
    bg: '#FFF0F3',
    textPrimary: '#3D0019',
    textSecondary: '#9E4B6E',
    textAccent: '#E8094A',
    btnBg: '#E8094A',
    btnText: '#FFFFFF',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#F4C2CE',
  },
  {
    id: 'minimal-sage',
    name: 'Sage',
    category: 'Minimal',
    emoji: '🌿',
    bg: '#2D3B2D',
    textPrimary: '#E8F0E8',
    textSecondary: '#8FAF8F',
    textAccent: '#7EC880',
    btnBg: '#7EC880',
    btnText: '#1A2E1A',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#3D4F3D',
  },
  {
    id: 'minimal-cream',
    name: 'Cream',
    category: 'Minimal',
    emoji: '🍦',
    bg: '#FFFBF0',
    textPrimary: '#3D3020',
    textSecondary: '#9A8060',
    textAccent: '#C4862A',
    btnBg: '#C4862A',
    btnText: '#FFFFFF',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#E8D8B8',
  },
  {
    id: 'minimal-navy',
    name: 'Deep Navy',
    category: 'Minimal',
    emoji: '🌊',
    bg: '#0D1B2A',
    textPrimary: '#FFFFFF',
    textSecondary: '#7A9BB5',
    textAccent: '#4FC3F7',
    btnBg: 'transparent',
    btnText: '#FFFFFF',
    btnBorder: '#4FC3F7',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#1A2D3D',
  },
  {
    id: 'minimal-forest',
    name: 'Forest',
    category: 'Minimal',
    emoji: '🌲',
    bg: '#1A2E1A',
    textPrimary: '#E8F5E8',
    textSecondary: '#6B9B6B',
    textAccent: '#90EE90',
    btnBg: 'transparent',
    btnText: '#90EE90',
    btnBorder: '#90EE90',
    btnRadius: 'sm',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#2A3E2A',
  },
  {
    id: 'minimal-clay',
    name: 'Clay',
    category: 'Minimal',
    emoji: '🏺',
    bg: '#E8C5A0',
    textPrimary: '#3D1F0A',
    textSecondary: '#8B5E3C',
    textAccent: '#3D1F0A',
    btnBg: '#3D1F0A',
    btnText: '#E8C5A0',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#C4A080',
  },

  // ─── NEON / GAMING ────────────────────────────────────────────────
  {
    id: 'neon-cyber',
    name: 'Cyberpunk',
    category: 'Neon',
    emoji: '🟢',
    bg: '#000000',
    textPrimary: '#00FF41',
    textSecondary: '#008F11',
    textAccent: '#00FF41',
    btnBg: 'transparent',
    btnText: '#00FF41',
    btnBorder: '#00FF41',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    glowColor: '#00FF4144',
    animated: true,
    animationType: 'glow',
    watermarkColor: '#003311',
  },
  {
    id: 'neon-purple',
    name: 'Neon Purple',
    category: 'Neon',
    emoji: '🟣',
    bg: '#0A0015',
    textPrimary: '#BF5FFF',
    textSecondary: '#7B2FBE',
    textAccent: '#BF5FFF',
    btnBg: 'transparent',
    btnText: '#BF5FFF',
    btnBorder: '#BF5FFF',
    btnRadius: 'sm',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    glowColor: '#BF5FFF44',
    animated: true,
    animationType: 'glow',
    watermarkColor: '#1A0030',
  },
  {
    id: 'neon-pink',
    name: 'Hot Pink',
    category: 'Neon',
    emoji: '🩷',
    bg: '#0D0010',
    textPrimary: '#FF0099',
    textSecondary: '#990066',
    textAccent: '#FF00CC',
    btnBg: '#FF0099',
    btnText: '#FFFFFF',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    glowColor: '#FF009944',
    animated: true,
    animationType: 'glow',
    watermarkColor: '#200020',
  },
  {
    id: 'neon-blue',
    name: 'Electric Blue',
    category: 'Neon',
    emoji: '🔵',
    bg: '#00010F',
    textPrimary: '#00B4FF',
    textSecondary: '#006B99',
    textAccent: '#00D4FF',
    btnBg: 'transparent',
    btnText: '#00D4FF',
    btnBorder: '#00D4FF',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    glowColor: '#00B4FF44',
    animated: true,
    animationType: 'glow',
    watermarkColor: '#000A1A',
  },
  {
    id: 'neon-orange',
    name: 'Neon Orange',
    category: 'Neon',
    emoji: '🟠',
    bg: '#0F0800',
    textPrimary: '#FF6B00',
    textSecondary: '#994000',
    textAccent: '#FF8C00',
    btnBg: '#FF6B00',
    btnText: '#000000',
    btnRadius: 'sm',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    glowColor: '#FF6B0044',
    animated: true,
    animationType: 'glow',
    watermarkColor: '#1A0D00',
  },
  {
    id: 'gaming-retro',
    name: 'Retro Arcade',
    category: 'Neon',
    emoji: '🕹️',
    bg: '#1A0033',
    textPrimary: '#FFFF00',
    textSecondary: '#CCCC00',
    textAccent: '#FF00FF',
    btnBg: '#FF00FF',
    btnText: '#000000',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#2D0052',
  },
  {
    id: 'gaming-dark',
    name: 'Dark Gaming',
    category: 'Neon',
    emoji: '🎮',
    bg: '#0F0F1A',
    textPrimary: '#FFFFFF',
    textSecondary: '#8888AA',
    textAccent: '#6C63FF',
    btnBg: '#6C63FF',
    btnText: '#FFFFFF',
    btnRadius: 'lg',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    decoration: 'dots',
    watermarkColor: '#1A1A2E',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'Neon',
    emoji: '🌐',
    bg: 'linear-gradient(135deg, #1a001a 0%, #0d0033 50%, #001a33 100%)',
    bgGradient: 'linear-gradient(135deg, #1a001a 0%, #0d0033 50%, #001a33 100%)',
    textPrimary: '#FF71CE',
    textSecondary: '#B967FF',
    textAccent: '#01CDFE',
    btnBg: 'transparent',
    btnText: '#01CDFE',
    btnBorder: '#01CDFE',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#2D0033',
  },

  // ─── BOLLYWOOD / DESI ─────────────────────────────────────────────
  {
    id: 'bollywood',
    name: 'Bollywood Editorial',
    category: 'Desi',
    emoji: '🎬',
    bg: '#0A0005',
    textPrimary: '#F5C842',
    textSecondary: '#8B7320',
    textAccent: '#F5C842',
    btnBg: 'transparent',
    btnText: '#F5C842',
    btnBorder: '#F5C842',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    decoration: 'diamonds',
    watermarkColor: '#2A1A00',
  },
  {
    id: 'bollywood-red',
    name: 'Shaadi Red',
    category: 'Desi',
    emoji: '❤️',
    bg: '#1A0000',
    textPrimary: '#FFD700',
    textSecondary: '#CC0000',
    textAccent: '#FFD700',
    btnBg: '#CC0000',
    btnText: '#FFD700',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    decoration: 'diamonds',
    watermarkColor: '#2A0000',
  },
  {
    id: 'bollywood-royal',
    name: 'Royal Nawab',
    category: 'Desi',
    emoji: '👑',
    bg: '#1A0033',
    textPrimary: '#FFD700',
    textSecondary: '#9966CC',
    textAccent: '#FFD700',
    btnBg: 'transparent',
    btnText: '#FFD700',
    btnBorder: '#FFD700',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    decoration: 'diamonds',
    watermarkColor: '#2A0044',
  },
  {
    id: 'marigold',
    name: 'Marigold Festival',
    category: 'Desi',
    emoji: '🌼',
    bg: '#FF6B00',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFE4B5',
    textAccent: '#FFD700',
    btnBg: '#FFD700',
    btnText: '#3D2000',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#CC5500',
  },
  {
    id: 'desi-modern',
    name: 'Modern Desi',
    category: 'Desi',
    emoji: '🪔',
    bg: '#FFFDF7',
    textPrimary: '#1A0A00',
    textSecondary: '#8B5E3C',
    textAccent: '#FF6B00',
    btnBg: '#FF6B00',
    btnText: '#FFFFFF',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#F5E8D5',
  },
  {
    id: 'rangoli',
    name: 'Rangoli',
    category: 'Desi',
    emoji: '🎨',
    bg: '#2D0A00',
    textPrimary: '#FF6B6B',
    textSecondary: '#FFB347',
    textAccent: '#FF6B6B',
    btnBg: 'transparent',
    btnText: '#FFB347',
    btnBorder: '#FFB347',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#3D1500',
  },

  // ─── PASTEL / AESTHETIC ───────────────────────────────────────────
  {
    id: 'pastel',
    name: 'Pastel Food Creator',
    category: 'Aesthetic',
    emoji: '🍰',
    bg: '#FDF6EC',
    textPrimary: '#8B5E3C',
    textSecondary: '#C89B7B',
    textAccent: '#E8593C',
    btnBg: '#FFFFFF',
    btnText: '#8B5E3C',
    btnBorder: '#F0DCC8',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#D4B896',
  },
  {
    id: 'pastel-blue',
    name: 'Baby Blue',
    category: 'Aesthetic',
    emoji: '🩵',
    bg: '#EEF6FF',
    textPrimary: '#1A3A5C',
    textSecondary: '#6B9EC4',
    textAccent: '#2F80ED',
    btnBg: '#FFFFFF',
    btnText: '#1A3A5C',
    btnBorder: '#BDD6F0',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#BDD6F0',
  },
  {
    id: 'pastel-lavender',
    name: 'Lavender Dream',
    category: 'Aesthetic',
    emoji: '💜',
    bg: '#F5F0FF',
    textPrimary: '#3D1F6E',
    textSecondary: '#9B72CF',
    textAccent: '#7B2FBE',
    btnBg: '#FFFFFF',
    btnText: '#3D1F6E',
    btnBorder: '#D4C0EE',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#D4C0EE',
  },
  {
    id: 'pastel-mint',
    name: 'Fresh Mint',
    category: 'Aesthetic',
    emoji: '🌱',
    bg: '#F0FFF4',
    textPrimary: '#1A3D2B',
    textSecondary: '#5A9A7A',
    textAccent: '#2ECC71',
    btnBg: '#FFFFFF',
    btnText: '#1A3D2B',
    btnBorder: '#B0E8C8',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#B0E8C8',
  },
  {
    id: 'pastel-peach',
    name: 'Peachy',
    category: 'Aesthetic',
    emoji: '🍑',
    bg: '#FFF5EE',
    textPrimary: '#5C2D0E',
    textSecondary: '#CC7A50',
    textAccent: '#FF6B35',
    btnBg: '#FF6B35',
    btnText: '#FFFFFF',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#F5CBB0',
  },
  {
    id: 'y2k-pink',
    name: 'Y2K Babe',
    category: 'Aesthetic',
    emoji: '💅',
    bg: '#FFB6C1',
    textPrimary: '#8B0057',
    textSecondary: '#CC3377',
    textAccent: '#FF1493',
    btnBg: '#FFFFFF',
    btnText: '#FF1493',
    btnBorder: '#FF69B4',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#FF69B4',
  },

  // ─── STREETWEAR / BOLD ────────────────────────────────────────────
  {
    id: 'streetwear',
    name: 'Streetwear',
    category: 'Bold',
    emoji: '🖤',
    bg: '#0A0A0A',
    textPrimary: '#FFFFFF',
    textSecondary: '#666666',
    textAccent: '#FFFFFF',
    btnBg: '#FFFFFF',
    btnText: '#000000',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#222222',
  },
  {
    id: 'streetwear-grey',
    name: 'Cement',
    category: 'Bold',
    emoji: '🩶',
    bg: '#1C1C1C',
    textPrimary: '#CCCCCC',
    textSecondary: '#666666',
    textAccent: '#FFFFFF',
    btnBg: 'transparent',
    btnText: '#CCCCCC',
    btnBorder: '#444444',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#2A2A2A',
  },
  {
    id: 'streetwear-red',
    name: 'Off-Court',
    category: 'Bold',
    emoji: '🔴',
    bg: '#0A0A0A',
    textPrimary: '#FFFFFF',
    textSecondary: '#888888',
    textAccent: '#FF0000',
    btnBg: '#FF0000',
    btnText: '#FFFFFF',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#1A0000',
  },
  {
    id: 'hypebeast',
    name: 'Hypebeast',
    category: 'Bold',
    emoji: '💥',
    bg: '#FFFFFF',
    textPrimary: '#000000',
    textSecondary: '#444444',
    textAccent: '#FF4500',
    btnBg: '#000000',
    btnText: '#FFFFFF',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#CCCCCC',
  },
  {
    id: 'grunge',
    name: 'Grunge',
    category: 'Bold',
    emoji: '🎸',
    bg: '#1A1209',
    textPrimary: '#D4C4A0',
    textSecondary: '#8B7355',
    textAccent: '#D4A017',
    btnBg: 'transparent',
    btnText: '#D4C4A0',
    btnBorder: '#8B7355',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#2A1A09',
  },

  // ─── VINTAGE / RETRO ──────────────────────────────────────────────
  {
    id: 'retro-90s',
    name: '90s Nostalgia',
    category: 'Retro',
    emoji: '📼',
    bg: '#F0E68C',
    textPrimary: '#4B0082',
    textSecondary: '#8B008B',
    textAccent: '#FF4500',
    btnBg: '#FF4500',
    btnText: '#FFFFFF',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#D4C870',
  },
  {
    id: 'dark-academia',
    name: 'Dark Academia',
    category: 'Retro',
    emoji: '📚',
    bg: '#1A1209',
    textPrimary: '#C8A96E',
    textSecondary: '#8B6914',
    textAccent: '#C8A96E',
    btnBg: 'transparent',
    btnText: '#C8A96E',
    btnBorder: '#8B6914',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    decoration: 'lines',
    watermarkColor: '#2A1F09',
  },
  {
    id: 'vintage-paper',
    name: 'Vintage Paper',
    category: 'Retro',
    emoji: '📜',
    bg: '#F4ECD8',
    textPrimary: '#2C1A0E',
    textSecondary: '#8B6914',
    textAccent: '#6B3A2A',
    btnBg: '#2C1A0E',
    btnText: '#F4ECD8',
    btnRadius: 'sm',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#D4C4A0',
  },
  {
    id: 'lo-fi',
    name: 'Lo-Fi',
    category: 'Retro',
    emoji: '🎧',
    bg: '#2D2B3D',
    textPrimary: '#E8D5B7',
    textSecondary: '#9B8EA0',
    textAccent: '#FF9EAA',
    btnBg: '#FF9EAA',
    btnText: '#2D2B3D',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    decoration: 'stars',
    watermarkColor: '#3D3B4D',
  },

  // ─── GRADIENT / ANIMATED ──────────────────────────────────────────
  {
    id: 'gradient-sunset',
    name: 'Sunset',
    category: 'Gradient',
    emoji: '🌅',
    bg: 'linear-gradient(135deg, #FF512F 0%, #DD2476 50%, #FF512F 100%)',
    bgGradient: 'linear-gradient(135deg, #FF512F 0%, #DD2476 100%)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFB3C6',
    textAccent: '#FFE4E1',
    btnBg: 'rgba(255,255,255,0.2)',
    btnText: '#FFFFFF',
    btnBorder: 'rgba(255,255,255,0.5)',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    animated: true,
    animationType: 'gradient',
    watermarkColor: 'rgba(255,255,255,0.3)',
  },
  {
    id: 'gradient-ocean',
    name: 'Ocean',
    category: 'Gradient',
    emoji: '🌊',
    bg: 'linear-gradient(135deg, #006994 0%, #0099CC 50%, #00CED1 100%)',
    bgGradient: 'linear-gradient(135deg, #006994 0%, #00CED1 100%)',
    textPrimary: '#FFFFFF',
    textSecondary: '#B0E0FF',
    textAccent: '#00FFFF',
    btnBg: 'rgba(255,255,255,0.2)',
    btnText: '#FFFFFF',
    btnBorder: 'rgba(255,255,255,0.5)',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    animated: true,
    animationType: 'gradient',
    watermarkColor: 'rgba(255,255,255,0.3)',
  },
  {
    id: 'gradient-aurora',
    name: 'Aurora',
    category: 'Gradient',
    emoji: '🌌',
    bg: 'linear-gradient(135deg, #0A0015 0%, #001A33 50%, #001A00 100%)',
    bgGradient: 'linear-gradient(135deg, #0A0015 0%, #001A00 100%)',
    textPrimary: '#00FF88',
    textSecondary: '#00AAFF',
    textAccent: '#00FF88',
    btnBg: 'transparent',
    btnText: '#00FF88',
    btnBorder: '#00FF88',
    btnRadius: 'sm',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    animated: true,
    animationType: 'gradient',
    watermarkColor: '#002211',
  },
  {
    id: 'gradient-rose-gold',
    name: 'Rose Gold',
    category: 'Gradient',
    emoji: '✨',
    bg: 'linear-gradient(135deg, #B76E79 0%, #E8B4B8 50%, #F7C59F 100%)',
    bgGradient: 'linear-gradient(135deg, #B76E79 0%, #F7C59F 100%)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFE8EC',
    textAccent: '#FFFFFF',
    btnBg: 'rgba(255,255,255,0.3)',
    btnText: '#FFFFFF',
    btnBorder: 'rgba(255,255,255,0.6)',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    animated: true,
    animationType: 'gradient',
    watermarkColor: 'rgba(255,255,255,0.3)',
  },
  {
    id: 'glass',
    name: 'Glass',
    category: 'Gradient',
    emoji: '🔮',
    bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    bgGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textPrimary: '#FFFFFF',
    textSecondary: 'rgba(255,255,255,0.7)',
    textAccent: '#FFFFFF',
    btnBg: 'rgba(255,255,255,0.15)',
    btnText: '#FFFFFF',
    btnBorder: 'rgba(255,255,255,0.4)',
    btnRadius: 'lg',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    animated: true,
    animationType: 'gradient',
    watermarkColor: 'rgba(255,255,255,0.3)',
  },

  // ─── PROFESSIONAL / CORPORATE ─────────────────────────────────────
  {
    id: 'corporate-clean',
    name: 'Executive',
    category: 'Professional',
    emoji: '💼',
    bg: '#FFFFFF',
    textPrimary: '#1A1A2E',
    textSecondary: '#4A4A6A',
    textAccent: '#0066CC',
    btnBg: '#0066CC',
    btnText: '#FFFFFF',
    btnRadius: 'sm',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#CCCCCC',
  },
  {
    id: 'corporate-dark',
    name: 'Dark Suite',
    category: 'Professional',
    emoji: '🌑',
    bg: '#0F172A',
    textPrimary: '#F8FAFC',
    textSecondary: '#94A3B8',
    textAccent: '#6366F1',
    btnBg: '#6366F1',
    btnText: '#FFFFFF',
    btnRadius: 'lg',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#1E293B',
  },
  {
    id: 'fitness',
    name: 'Fitness Mode',
    category: 'Professional',
    emoji: '💪',
    bg: '#0A0A0A',
    textPrimary: '#FFFFFF',
    textSecondary: '#888888',
    textAccent: '#FF4500',
    btnBg: '#FF4500',
    btnText: '#FFFFFF',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    watermarkColor: '#1A0A00',
  },
  {
    id: 'wellness',
    name: 'Wellness',
    category: 'Professional',
    emoji: '🧘',
    bg: '#F8F5F0',
    textPrimary: '#3D3020',
    textSecondary: '#9A8060',
    textAccent: '#7BAF7B',
    btnBg: '#7BAF7B',
    btnText: '#FFFFFF',
    btnRadius: 'full',
    btnStyle: 'solid',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    watermarkColor: '#D4C8B8',
  },
  {
    id: 'art-gallery',
    name: 'Art Gallery',
    category: 'Professional',
    emoji: '🖼️',
    bg: '#FAFAFA',
    textPrimary: '#000000',
    textSecondary: '#666666',
    textAccent: '#000000',
    btnBg: 'transparent',
    btnText: '#000000',
    btnBorder: '#000000',
    btnRadius: 'none',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    decoration: 'lines',
    watermarkColor: '#CCCCCC',
  },

  // ─── MUSIC / ARTIST ───────────────────────────────────────────────
  {
    id: 'vinyl-dark',
    name: 'Vinyl',
    category: 'Music',
    emoji: '🎵',
    bg: '#0D0D0D',
    textPrimary: '#FFFFFF',
    textSecondary: '#888888',
    textAccent: '#E8593C',
    btnBg: 'transparent',
    btnText: '#FFFFFF',
    btnBorder: '#333333',
    btnRadius: 'full',
    btnStyle: 'outline',
    fontDisplay: 'DM Sans',
    fontBody: 'DM Sans',
    decoration: 'dots',
    watermarkColor: '#1A1A1A',
  },
  {
    id: 'concert',
    name: 'Concert',
    category: 'Music',
    emoji: '🎤',
    bg: '#000000',
    textPrimary: '#FFFFFF',
    textSecondary: '#AAAAAA',
    textAccent: '#FFD700',
    btnBg: '#FFD700',
    btnText: '#000000',
    btnRadius: 'none',
    btnStyle: 'solid',
    fontDisplay: 'Bebas Neue',
    fontBody: 'DM Sans',
    decoration: 'stars',
    watermarkColor: '#1A1A00',
  },
]

export function getTemplate(id: string): TemplateConfig {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES.find((t) => t.id === 'streetwear')!
}

export const TEMPLATE_CATEGORIES = [
  'Minimal',
  'Neon',
  'Desi',
  'Aesthetic',
  'Bold',
  'Retro',
  'Gradient',
  'Professional',
  'Music',
]
